### ISSUE TITLE
I got Can't resolve '@popperjs/core' error installing the app...

### ISSUE THREAD

**Issue by sergeynilov** [sinan-aydogan/anemon-laravel#3]
Hello,
Trying to install fresh version of sinan-aydogan/anemon-laravel
I got errors with command : 

```
master@master-laptop:/mnt/_work_sdb8/wwwroot/lar/AdsAnemon$ npm run hot

> @ hot /mnt/_work_sdb8/wwwroot/lar/AdsAnemon
> mix watch --hot


✖ Mix
  Compiled with some errors in 23.43s

[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.


● Mix █████████████████████████ done (99%) plugins 
 webpack-dev-server

ERROR in ./node_modules/v-calendar/lib/esm/Popover.vue_vue&type=style&index=0&id=5059a25e&lang-859ee3d7.js 3:0-46
Module not found: Error: Can't resolve '@popperjs/core' in '/mnt/_work_sdb8/wwwroot/lar/AdsAnemon/node_modules/v-calendar/lib/esm'

ERROR in ./node_modules/v-calendar/lib/esm/index.js 6:0-24
Module not found: Error: Can't resolve '@popperjs/core' in '/mnt/_work_sdb8/wwwroot/lar/AdsAnemon/node_modules/v-calendar/lib/esm'

webpack compiled with 2 errors
```

I tried to fix this problem with command :

`npm install popper.js --save`

But running npm run hot I got the same errors again...

I really wander  does this projects needs popperjs installed ? Usually it is used by jquery
and jquery is not what I expect in vuejs3 project...

https://prnt.sc/26ktae4
AND
https://prnt.sc/26kthau

Which steps have I to take to run the app?

Thanks!

**Comment by sinan-aydogan** [comment]
Please, can you share nodejs version ? I checked by clear setup and I didn't catch this bug.

**Comment by sergeynilov** [comment]
node -v
v14.18.1

$ npm -v
6.14.15

**Comment by sinan-aydogan** [comment]
Can you join : [TailAdmin Discord Channel](https://discord.gg/VWs8Yp8q)

**Comment by sergeynilov** [comment]
I commented line 
  import { DatePicker } from 'v-calendar'
and moved next. Maybe later I will return to it when I need v-calendar

**Comment by sinan-aydogan** [comment]
Problem solved, please check last commits. Firstly delete public/js/date-picker.umd.js.map then please change files with updated files. 

- [public/js/date-picker.umd.js.map deleted](https://github.com/sinan-aydogan/anemon-laravel/commit/85cad23c13862af37acfaf4bfe632a126553d98b)
- [upgrades date input component to vue3 and v-calendar method updated](https://github.com/sinan-aydogan/anemon-laravel/commit/19916ead75fac6fb09e9969b6c23befc8a8bfe11)
- [fixes form component config errors](https://github.com/sinan-aydogan/anemon-laravel/commit/5bf55590e792a559e27ce9d48109e4c2ed9a3ef5)
- [adds date input and form content config properties](https://github.com/sinan-aydogan/anemon-laravel/commit/9660c52aa7b9838812c8859041304cb6a9091732)

**Comment by sergeynilov** [comment]
Thanks! Now all work ok.
