### ISSUE TITLE
Command: php artisan storage:link

### ISSUE THREAD

**Issue by b1tw0rker** [sinan-aydogan/anemon-laravel#5]
php artisan storage:link procuces the followinf error on a linux/centos machine:

   ErrorException

  symlink(): Operation not permitted

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:332
    328▕      */
    329▕     public function link($target, $link)
    330▕     {
    331▕         if (! windows_os()) {
  ➜ 332▕             return symlink($target, $link);
    333▕         }
    334▕
    335▕         $mode = $this->isDirectory($target) ? 'J' : 'H';
    336▕

      +15 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by sinan-aydogan** [comment]
Hi,

 If you're working in Linux, you need to change folder permissions.

PROJECTFOLDERDIRECTORY example: /var/www/anemon

- rm PROJECTFOLDERDIRECTORY/storage
- chmod -R 755 PROJECTFOLDERDIRECTORY
- chmod -R 755 PROJECTFOLDERDIRECTORY/storage
- chcon -R -t httpd_sys_rw_content_t /var/www/PROJECTFOLDERDIRECTORY/storage
- cd /var/www/PROJECTFOLDERDIRECTORY
- php artisan storage:link
