### ISSUE TITLE
Goto: http://localhost:8000 or your APP_URL (in the .ENV

### ISSUE THREAD

**Issue by b1tw0rker** [sinan-aydogan/anemon-laravel#6]
Changing APP_URL does not contain changes in the command line:

I had do do the following to start the app with other IP than localhost:

php artisan serve --host=192.168.0.1 (e.g. some other IP)

**Comment by emredipi** [comment]
APP_URL doesn't change your host URL. If you want to open the project in the browser with APP_URL you have to add it to `/etc/hosts` file.

eg:
`127.0.0.1 example.com`
